# Generated by Django 4.0.1 on 2022-01-31 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
    ]
